### ISSUE TITLE
Set Up a "Hello World" VSCode Extension and Document the Process

### ISSUE THREAD

**Issue by NLaundry** [Intelligent-Adaptive-Interventions-Lab/VSCode-Jupyter-Datamining-Extension#1]
**Description:**

Set up a basic "Hello World" VSCode extension as a starting point for the JupyterNotebook Execution Analyzer extension. Document the entire setup process, explaining all the choices made during setup and any configuration changes required.

**Tasks:**

- Create a new VSCode extension using the Yeoman generator.
- Choose appropriate options during the setup process (e.g., extension name, description, publisher, and language).
- Modify the extension to display a "Hello World" message when the command is triggered.
- Test the "Hello World" extension in VSCode to ensure it works correctly.
- Document the entire setup process, explaining the choices made during setup and any configuration changes required.

**Acceptance Criteria:**

- A basic "Hello World" VSCode extension should be created as a starting point for the JupyterNotebook Execution Analyzer extension.
- The extension should display a "Hello World" message when the command is triggered.
- The entire setup process should be documented, including the choices made during setup and any configuration changes required.
- The documentation should be clear, concise, and easily understandable by other team members.

**Comment by steventohme** [comment]
Hey @Intelligent-Adaptive-Interventions-Lab/instructor-ai-colab  I've attached the process for creating the VSCode extension. Let me know if I should make any changes. Once we decide on a name for the extension i'll commit the extension files to the repo.

# VSCode Extension Start-UP

1. **Installing Dependencies** ⚓️
    - Make sure you have the following installed:
        - [Node.js](https://nodejs.org/en)
        - [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
        - [Yarn](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable)
    
2. **Installing Yeoman and VSCode Extension Generator** 🏗
    - Install both using: 'npm install -g yo generator-code'
    - You can also install one at a time if that tickles your fancy using, 'npm install -g yo' and npm 'install -g generator-code'
    - If you get an error using MacOS/Linux, use 'sudo npm install -g yo generator-code' instead

3. **Choosing Extension Settings** ⚙️
    - navigate to the directory you want the extension to be in
    - run Yeoman by using the 'yo code' command in your terminal
    - Select JavaScript as the language of choice
    - Set the name to 'helloWorld'
    - Set the identifier to something that will be easy to call
    - Leave the description blank
    - Don't set up JavaScript type checking
    - Don't set up a Git repo
    - Use Yarn as the package installer

### You now have a VSCode Extension. Congratulations! 🎉
