### ISSUE TITLE
Document Contribution Steps Including Branching, Merging, etc.

### ISSUE THREAD

**Issue by NLaundry** [Intelligent-Adaptive-Interventions-Lab/VSCode-Jupyter-Datamining-Extension#2]
**Description:**

Create a comprehensive guide that documents the contribution steps for team members working on the JupyterNotebook Execution Analyzer extension. The guide should cover branching off a ticket, handling merges, and any other relevant steps to ensure a smooth development process.

**Tasks:**

- Write an introduction to the contribution guide, explaining its purpose and importance.
- Document the process of creating a new branch for a ticket, including naming conventions and the commands required.
- Explain the process of committing changes and pushing the branch to the remote repository.
- Describe the process of creating a pull request for the changes made in the branch, including a clear description of the changes and referencing the relevant ticket.
- Outline the code review process, including requesting reviews, addressing feedback, and incorporating changes.
- Explain the process of merging the pull request, resolving any merge conflicts, and deleting the branch after a successful merge.
- Provide any additional guidelines or best practices for the team to follow during the development process.

**Acceptance Criteria:**

- The contribution guide should cover all relevant steps in the development process, including branching, merging, and more.
- The guide should be clear, concise, and easily understandable by all team members.
- The guide should promote best practices and consistency among team members in the development process.

**Comment by aidantrabs** [comment]
I'm going to separate the contribution guide from the usual README - I want to use the README for a shorter overview of the project, easy installation etc.
