### ISSUE TITLE
Implement a Command to Count the Number of Times a Cell is Run

### ISSUE THREAD

**Issue by NLaundry** [Intelligent-Adaptive-Interventions-Lab/VSCode-Jupyter-Datamining-Extension#3]
Description:

Create a simple command in the JupyterNotebook Execution Analyzer extension that counts the number of times a Jupyter notebook cell is run. This command should display the count in the VSCode Output panel for the user to see.

**Pseudocode:**

- Initialize a cell execution counter (e.g., an object mapping cell IDs to counts).
- Listen for the execution event of a Jupyter notebook cell.
- When a cell execution event is detected:
- a. Increment the corresponding count in the cell execution counter object.
- b. Display the updated count in the VSCode Output panel.

Acceptance Criteria:

- The command should correctly count the number of times each cell is run.
- The count should be displayed in the VSCode Output panel.
- The code should be written in TypeScript and comply with the project's coding standards.

**Comment by juancwu** [comment]
I will do some research on this and see what I can come up with.
